
default: &default
  adapter: postgresql
  encoding: unicode
  database: app_for_audiences_development
  host: db
  username: postgres
  password: <%= ENV['DATABASE_PASSWORD'] %> 
  pool: 5

development:
  <<: *default
  database: app_for_audiences_development

test:
  <<: *default
  database: app_for_audiences_test

production:
  <<: *default
  database: app_for_audiences_production
